import Link from 'next/link';
import { Sidebar } from '../../components/Sidebar';
import { createClient } from '../../lib/supabase/server';
import { requireActiveWorkspace } from '../../lib/workspaces/session';
import { queueDiscovery, runControlledDiscovery } from './actions';

export const dynamic='force-dynamic';

export default async function DiscoverPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const [workspace,query]=await Promise.all([requireActiveWorkspace(),searchParams]);
  const supabase=await createClient();
  const [profilesResult,runsResult,jobsResult,usageResult]=await Promise.all([
    supabase.from('offer_profiles').select('*').eq('workspace_id',workspace.id).eq('active',true).order('priority'),
    supabase.from('discovery_runs').select('id,status,source_names,started_at,completed_at,accounts_discovered,signals_discovered,error_count,offer_profile_id,metadata').eq('workspace_id',workspace.id).order('started_at',{ascending:false}).limit(10),
    supabase.from('durable_jobs').select('id,status,attempt_count,max_attempts,created_at,last_error,payload').eq('workspace_id',workspace.id).eq('job_type','discovery').order('created_at',{ascending:false}).limit(8),
    supabase.from('provider_usage').select('provider,action,units,occurred_at,offer_profile_id,metadata').eq('workspace_id',workspace.id).order('occurred_at',{ascending:false}).limit(100),
  ]);
  const profiles:any[]=profilesResult.data||[]; const active=profiles[0]; const runs:any[]=runsResult.data||[]; const jobs:any[]=jobsResult.data||[]; const usage:any[]=usageResult.data||[];
  const canOperate=['owner','admin','member'].includes(workspace.role); const canRun=['owner','admin'].includes(workspace.role);
  const crustdataConfigured=Boolean(process.env.CRUSTDATA_API_KEY); const anthropicConfigured=Boolean(process.env.ANTHROPIC_API_KEY);
  const recentCrust=usage.filter(u=>u.provider==='crustdata').slice(0,30).reduce((sum,u)=>sum+Number(u.units||0),0);
  return <div className="shell premiumShell"><Sidebar/><main className="commandMain"><header className="commandHeader"><div><div className="eyebrow">Find leads</div><h1>Search for companies already hiring for work you can sell.</h1><p>Choose the offer. We find fresh job posts, check the company, find the likely buyer, verify a work email, and prepare a message for your review.</p></div><Link className="ghost" href="/settings/offers">Edit what I sell</Link></header>
  {query.error?<div className="commandAlert"><strong>Search could not run</strong><span>{query.error}</span></div>:null}{query.notice?<div className="commandAlert"><strong>{query.notice}</strong></div>:null}
  <section className="commandKpis simpleKpis"><div><span>Lead source</span><strong>{crustdataConfigured?'Ready':'Connect'}</strong><small>Crustdata jobs, companies and people</small></div><div><span>Message writer</span><strong>{anthropicConfigured?'Ready':'Connect'}</strong><small>Claude drafts for your review</small></div><div><span>Active offers</span><strong>{profiles.length}</strong><small>{active?.name||'Create your first offer'}</small></div><div><span>Credits used</span><strong>{recentCrust.toFixed(1)}</strong><small>Recent Crustdata usage</small></div></section>
  {active?<section className="searchLaunchCard"><div className="searchLaunchMain"><span className="signalBadge">Active search</span><h2>{active.name}</h2><p>{active.target_countries?.join(' and ')} · jobs posted in the last {active.lookback_days} days</p><div className="searchRule"><span>Looking for</span><strong>{(active.target_job_titles||[]).slice(0,6).join(' · ')}</strong>{(active.target_job_titles||[]).length>6?<small>+ {(active.target_job_titles||[]).length-6} more job titles</small>:null}</div><div className="searchCaps"><span>Up to {active.caps?.jobsPerRun||25} job posts</span><span>Up to {active.caps?.contactsPerRun||25} people lookups</span><span>Max {active.caps?.creditsPerRun||60} credits</span></div></div><aside className="searchLaunchAction"><span className="eyebrow">What happens next</span><ol><li>Find fresh jobs</li><li>Remove poor-fit companies</li><li>Find the right person</li><li>Verify their work email</li><li>Prepare a message for you</li></ol>{canRun?<form action={runControlledDiscovery}><input type="hidden" name="offerProfileId" value={active.id}/><button className="primary" type="submit" disabled={!crustdataConfigured}>Find leads now</button></form>:null}{canOperate?<form action={queueDiscovery} className="secondaryRun"><input type="hidden" name="offerProfileId" value={active.id}/><button className="ghost" type="submit">Run in background</button></form>:null}<small>Nothing is sent automatically.</small></aside></section>:<section className="revenueEmpty"><h2>Create an offer before searching.</h2><p>An offer tells Revenue Agent which jobs matter, what companies fit, who to look for, and what you sell instead of the hire.</p><Link className="primary" href="/settings/offers">Create offer</Link></section>}
  <section className="storyPanel"><div className="commandSectionHead"><div><span className="eyebrow">Search history</span><h2>Recent lead searches</h2></div></div>{runsResult.error?<p>Search history is temporarily unavailable.</p>:runs.length?<div className="storyList">{runs.map(run=><div className="storyRow" key={run.id}><span>{String(run.status).replaceAll('_',' ')}</span><strong>{new Date(run.started_at).toLocaleString()} · {run.accounts_discovered||0} companies found</strong><span>{run.error_count?`${run.error_count} issues`:'Completed cleanly'}</span></div>)}</div>:<p>No searches have run yet.</p>}</section>
  <section className="storyPanel"><div className="commandSectionHead"><div><span className="eyebrow">Background searches</span><h2>Jobs still running or waiting</h2></div></div>{jobsResult.error?<p>Background status is temporarily unavailable.</p>:jobs.length?<div className="storyList">{jobs.map(job=><div className="storyRow" key={job.id}><span>{String(job.status).replaceAll('_',' ')}</span><strong>{new Date(job.created_at).toLocaleString()}</strong><span>{job.last_error||`Attempt ${job.attempt_count}/${job.max_attempts}`}</span></div>)}</div>:<p>Nothing is waiting in the background.</p>}</section>
  </main></div>;
}
