import Link from 'next/link';
import { Sidebar } from '../../components/Sidebar';
import { createClient } from '../../lib/supabase/server';
import { requireActiveWorkspace } from '../../lib/workspaces/session';
import { queueDiscovery, runControlledDiscovery } from './actions';

export const dynamic='force-dynamic';

export default async function DiscoverPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const [workspace,query]=await Promise.all([requireActiveWorkspace(),searchParams]);
  const supabase=await createClient();
  const [profilesResult,runsResult,jobsResult,usageResult]=await Promise.all([
    supabase.from('offer_profiles').select('*').eq('workspace_id',workspace.id).eq('active',true).order('priority'),
    supabase.from('discovery_runs').select('id,status,source_names,started_at,completed_at,accounts_discovered,signals_discovered,error_count,offer_profile_id,metadata').eq('workspace_id',workspace.id).order('started_at',{ascending:false}).limit(10),
    supabase.from('durable_jobs').select('id,status,attempt_count,max_attempts,created_at,last_error,payload').eq('workspace_id',workspace.id).eq('job_type','discovery').order('created_at',{ascending:false}).limit(8),
    supabase.from('provider_usage').select('provider,action,units,occurred_at,offer_profile_id,metadata').eq('workspace_id',workspace.id).order('occurred_at',{ascending:false}).limit(100),
  ]);
  const profiles:any[]=profilesResult.data||[]; const active=profiles[0]; const runs:any[]=runsResult.data||[]; const jobs:any[]=jobsResult.data||[]; const usage:any[]=usageResult.data||[];
  const canOperate=['owner','admin','member'].includes(workspace.role); const canRun=['owner','admin'].includes(workspace.role);
  const crustdataConfigured=Boolean(process.env.CRUSTDATA_API_KEY); const anthropicConfigured=Boolean(process.env.ANTHROPIC_API_KEY);
  const recentCrust=usage.filter(u=>u.provider==='crustdata').slice(0,30).reduce((sum,u)=>sum+Number(u.units||0),0);
  return <div className="shell premiumShell"><Sidebar/><main className="commandMain"><header className="commandHeader"><div><div className="eyebrow">Hiring-led discovery</div><h1>Find companies already telling us they need ecommerce talent.</h1><p>Job postings are the primary trigger. Storefront and company signals only strengthen scoring and personalize the message.</p></div><Link className="ghost" href="/settings/offers">Edit offer profiles</Link></header>
  {query.error?<div className="commandAlert"><strong>Run blocked</strong><span>{query.error}</span></div>:null}{query.notice?<div className="commandAlert"><strong>{query.notice}</strong></div>:null}
  <section className="commandKpis"><div><span>Crustdata</span><strong>{crustdataConfigured?'Ready':'Key needed'}</strong><small>Primary job + buyer + verified work-email provider</small></div><div><span>Claude</span><strong>{anthropicConfigured?'Ready':'Key needed'}</strong><small>Drafting only · no autonomous send</small></div><div><span>Offer profiles</span><strong>{profiles.length}</strong><small>{active?.name||'Create an active profile'}</small></div><div><span>Recorded Crustdata credits</span><strong>{recentCrust.toFixed(2)}</strong><small>Recent provider-usage receipts</small></div></section>
  {active?<section className="revenueSpotlight"><div className="revenueSpotlightMain"><div className="signalBadge">Primary trigger · hiring</div><div className="spotlightTop"><div><h2>{active.name}</h2><p>{active.target_countries?.join(' + ')} · last {active.lookback_days} days</p></div><div className="opportunityNumber"><strong>{active.caps?.jobsPerRun||25}</strong><span>max jobs / run</span></div></div><div className="hiringReason"><span>Titles searched</span><h3>{(active.target_job_titles||[]).slice(0,5).join(' · ')}</h3><p>{(active.target_job_titles||[]).length>5?`+ ${(active.target_job_titles||[]).length-5} additional configured titles. `:''}Staffing, recruiters and agencies are excluded by profile rules.</p></div><div className="spotlightEvidence"><div><span>Job cap</span><strong>{active.caps?.jobsPerRun||25}</strong></div><div><span>Contact cap</span><strong>{active.caps?.contactsPerRun||25}</strong></div><div><span>Credit cap</span><strong>{active.caps?.creditsPerRun||60}</strong></div></div></div><aside className="revenueSpotlightAside"><span className="eyebrow">Controlled batch</span><h3>Jobs → company → buyer → verified email → held draft.</h3><p>The run uses Crustdata first. Claude drafts only after a verified professional email exists. Nothing sends.</p>{canRun?<form action={runControlledDiscovery}><input type="hidden" name="offerProfileId" value={active.id}/><button className="primary" type="submit" disabled={!crustdataConfigured}>Run controlled batch now</button></form>:null}{canOperate?<form action={queueDiscovery} style={{marginTop:10}}><input type="hidden" name="offerProfileId" value={active.id}/><button className="ghost" type="submit">Queue durable run</button></form>:null}<small className="safetyNote">Hard maximum 25 job results and 25 contact lookups per run.</small></aside></section>:<section className="revenueEmpty"><h2>No active offer profile.</h2><p>Create one before discovery can run.</p><Link className="primary" href="/settings/offers">Create offer profile</Link></section>}
  <section className="storyPanel"><div className="commandSectionHead"><div><span className="eyebrow">Recent runs</span><h2>What the engine actually did</h2></div></div>{runsResult.error?<p>Run history unavailable.</p>:runs.length?<div className="storyList">{runs.map(run=><div className="storyRow" key={run.id}><span>{String(run.status).replaceAll('_',' ')}</span><strong>{new Date(run.started_at).toLocaleString()} · {run.accounts_discovered||0} accounts · {run.signals_discovered||0} signals · {run.error_count||0} errors</strong><span>{run.metadata?.offerProfileKey||'profile run'}</span></div>)}</div>:<p>No live run has completed yet.</p>}</section>
  <section className="storyPanel"><div className="commandSectionHead"><div><span className="eyebrow">Durable queue</span><h2>Background work state</h2></div></div>{jobsResult.error?<p>Queue state unavailable.</p>:jobs.length?<div className="storyList">{jobs.map(job=><div className="storyRow" key={job.id}><span>{String(job.status).replaceAll('_',' ')}</span><strong>{new Date(job.created_at).toLocaleString()} · attempt {job.attempt_count}/{job.max_attempts}</strong><span>{job.last_error||'No error'}</span></div>)}</div>:<p>No queued jobs.</p>}</section>
  <section className="commandFooterGrid"><article><span className="eyebrow">Source policy</span><h3>Crustdata first. Greenhouse and Lever stay secondary.</h3><p>StoreLeads and BuiltWith remain optional and are not required for the DCL offer profile.</p></article><article><span className="eyebrow">Spend policy</span><h3>Every provider call leaves a usage receipt.</h3><p>The worker records Crustdata response-credit usage and stops research when the configured run/day/week caps are reached.</p></article></section>
  </main></div>;
}
