import Link from 'next/link';
import { Sidebar } from '../../components/Sidebar';
import { createClient } from '../../lib/supabase/server';
import { requireActiveWorkspace } from '../../lib/workspaces/session';
import { PIPELINE_STAGES } from '../../lib/pipeline/stages';
import { updatePipeline } from './actions';
export const dynamic = 'force-dynamic';
export default async function Pipeline({searchParams}: {searchParams: Promise<{error?:string;notice?:string}>}) {
  const workspace = await requireActiveWorkspace(); const params = await searchParams; const supabase = await createClient();
  const [accounts,events] = await Promise.all([supabase.from('accounts').select('id,name,domain,pipeline_stage,pipeline_revision,next_action,next_action_due,suppressed').eq('workspace_id',workspace.id).order('next_action_due',{ascending:true,nullsFirst:false}).limit(100),supabase.from('pipeline_events').select('id,account_id,previous_stage,stage,next_action,recorded_at').eq('workspace_id',workspace.id).order('recorded_at',{ascending:false}).limit(12)]);
  const canEdit = ['owner','admin','member'].includes(workspace.role); const rows = accounts.data || [];
  return <div className="shell premiumShell"><Sidebar/><main className="commandMain"><header className="commandHeader"><div><div className="eyebrow">Pipeline</div><h1>Know exactly what happens next.</h1><p>Move good leads forward, record the next step, and keep promising opportunities from going cold.</p></div><Link className="ghost" href="/accounts">View leads</Link></header>
    {params.error || params.notice ? <section className="commandAlert" role="status"><strong>{params.error ? 'Could not save' : 'Saved'}</strong><span>{params.error || params.notice}</span></section> : null}
    {accounts.error ? <section className="panel noticePanel" role="alert"><div className="eyebrow">Pipeline unavailable</div><h2>We could not load your stages.</h2><p>Try again shortly.</p><Link className="inlineAction" href="/pipeline">Reload</Link></section> : <><section className="pipelineSummary" aria-label="Pipeline stages">{PIPELINE_STAGES.map(stage=><div key={stage}><span>{stage}</span><strong>{rows.filter(account=>account.pipeline_stage===stage).length}</strong></div>)}</section><p className="pipelineCaption">Keep each lead moving with one clear next action. {canEdit ? 'Every saved change is tracked.' : 'Your access is read-only.'}</p>
    {!rows.length ? <section className="panel emptyState"><div className="eyebrow">No pipeline yet</div><h2>Start with a lead worth pursuing.</h2><p>Once you review a lead and decide it matters, track the next step here.</p><Link className="primary inlineAction" href="/accounts">View leads</Link></section> : <section className="pipelineStack">{rows.map(account=><article className="panel pipelineCard" key={account.id}><div className="panelHead"><div><Link href={`/accounts/${account.id}`}><h2>{account.name}</h2></Link><p>{account.domain}</p></div><span className="pill">{account.suppressed ? 'Do not contact' : account.pipeline_stage}</span></div>{account.suppressed ? <div className="partialState"><strong>Do not contact</strong><span>Outreach is blocked for this company.</span></div> : null}{canEdit ? <form action={updatePipeline} className="pipelineForm"><input type="hidden" name="accountId" value={account.id}/><input type="hidden" name="revision" value={account.pipeline_revision}/><label>Stage<select name="stage" defaultValue={account.pipeline_stage}>{PIPELINE_STAGES.filter(stage=>!account.suppressed || stage==='lost').map(stage=><option key={stage} value={stage}>{stage}</option>)}</select></label><label>Next step<input name="nextAction" maxLength={1000} defaultValue={account.next_action} placeholder="e.g. Review draft with Nouman"/></label><label>Due<input type="date" name="due" defaultValue={account.next_action_due || ''}/></label><button className="primary">Save</button></form> : <p>{account.next_action || 'No next step recorded.'}{account.next_action_due ? ` · Due ${account.next_action_due}` : ''}</p>}</article>)}</section>}</>}
    <section className="panel"><span className="eyebrow">Recent activity</span><h2>What moved</h2>{events.error ? <div className="emptyState"><strong>Activity is temporarily unavailable.</strong></div> : events.data?.length ? <div className="evidenceList">{events.data.map(event=><div className="evidenceItem" key={event.id}><div><Link href={`/accounts/${event.account_id}`}>Open lead</Link><strong>{event.previous_stage} → {event.stage}</strong><small>{event.next_action || 'No next step'} · {new Date(event.recorded_at).toLocaleString('en-US',{timeZone:'UTC'})} UTC</small></div></div>)}</div> : <div className="emptyState"><strong>No pipeline changes yet.</strong></div>}</section>
  </main></div>;
}
