import Link from 'next/link';
import { Sidebar } from '../../components/Sidebar';
import { createClient } from '../../lib/supabase/server';
import { requireActiveWorkspace } from '../../lib/workspaces/session';
import { PIPELINE_STAGES } from '../../lib/pipeline/stages';
import { updatePipeline } from './actions';
export const dynamic = 'force-dynamic';

export default async function Pipeline({searchParams}: {searchParams: Promise<{error?:string;notice?:string}>}) {
  const workspace = await requireActiveWorkspace(); const params = await searchParams; const supabase = await createClient();
  const [accounts,events] = await Promise.all([
    supabase.from('accounts').select('id,name,domain,pipeline_stage,pipeline_revision,next_action,next_action_due,suppressed,opportunity_score').eq('workspace_id',workspace.id).order('next_action_due',{ascending:true,nullsFirst:false}).limit(100),
    supabase.from('pipeline_events').select('id,account_id,previous_stage,stage,next_action,recorded_at').eq('workspace_id',workspace.id).order('recorded_at',{ascending:false}).limit(12)
  ]);
  const canEdit = ['owner','admin','member'].includes(workspace.role); const rows:any[] = accounts.data || [];
  return <div className="shell premiumShell"><Sidebar/><main className="commandMain"><header className="commandHeader"><div><div className="eyebrow">Pipeline</div><h1>See the whole sales motion at a glance.</h1><p>Move leads forward, keep the next action visible, and spot where deals are getting stuck.</p></div><Link className="ghost" href="/accounts">View leads</Link></header>
    {params.error || params.notice ? <section className="commandAlert" role="status"><strong>{params.error ? 'Could not save' : 'Saved'}</strong><span>{params.error || params.notice}</span></section> : null}
    {accounts.error ? <section className="panel noticePanel" role="alert"><div className="eyebrow">Pipeline unavailable</div><h2>We could not load your stages.</h2><p>Try again shortly.</p><Link className="inlineAction" href="/pipeline">Reload</Link></section> : rows.length ? <section className="pipelineBoard" aria-label="Sales pipeline board">{PIPELINE_STAGES.map(stage=>{
      const stageRows=rows.filter(account=>account.pipeline_stage===stage);
      return <div className="pipelineColumn" key={stage}><div className="pipelineColumnHead"><div><span>{stage}</span><strong>{stageRows.length}</strong></div><small>{stageRows.filter(a=>a.next_action_due).length} with due date</small></div><div className="pipelineColumnBody">{stageRows.map(account=><article className="pipelineLeadCard" key={account.id}><div className="pipelineLeadTop"><div><Link href={`/accounts/${account.id}`}><strong>{account.name}</strong></Link><small>{account.domain}</small></div><span>{account.opportunity_score??'—'}</span></div>{account.suppressed?<div className="pipelineSuppressed">Do not contact</div>:null}<div className="pipelineNext"><span>Next</span><strong>{account.next_action||'No next step yet'}</strong>{account.next_action_due?<small>Due {account.next_action_due}</small>:null}</div>{canEdit?<details className="pipelineQuickEdit"><summary>Update</summary><form action={updatePipeline}><input type="hidden" name="accountId" value={account.id}/><input type="hidden" name="revision" value={account.pipeline_revision}/><label>Stage<select name="stage" defaultValue={account.pipeline_stage}>{PIPELINE_STAGES.filter(s=>!account.suppressed||s==='lost').map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Next step<input name="nextAction" maxLength={1000} defaultValue={account.next_action} placeholder="What happens next?"/></label><label>Due<input type="date" name="due" defaultValue={account.next_action_due||''}/></label><button className="primary">Save</button></form></details>:null}</article>)}</div></div>})}</section> : <section className="panel emptyState"><div className="eyebrow">No pipeline yet</div><h2>Start with a lead worth pursuing.</h2><p>Once you review a lead and decide it matters, track the next step here.</p><Link className="primary inlineAction" href="/accounts">View leads</Link></section>}
    <section className="panel pipelineActivity"><span className="eyebrow">Recent activity</span><h2>What moved</h2>{events.error ? <div className="emptyState"><strong>Activity is temporarily unavailable.</strong></div> : events.data?.length ? <div className="evidenceList">{events.data.map(event=><div className="evidenceItem" key={event.id}><div><Link href={`/accounts/${event.account_id}`}>Open lead</Link><strong>{event.previous_stage} → {event.stage}</strong><small>{event.next_action || 'No next step'} · {new Date(event.recorded_at).toLocaleString('en-US',{timeZone:'UTC'})} UTC</small></div></div>)}</div> : <div className="emptyState"><strong>No pipeline changes yet.</strong></div>}</section>
  </main></div>;
}
