import Link from 'next/link';
import { Sidebar } from '../components/Sidebar';
import { ScoreRing } from '../components/ScoreRing';
import { rankObservedChange, rankPipelineChange } from '../lib/change-intelligence.js';
import { createClient } from '../lib/supabase/server';
import { requireActiveWorkspace } from '../lib/workspaces/session';

export const dynamic = 'force-dynamic';

type Account = { id:string; name:string; domain:string; opportunity_score:number|null; tier:string|null; suggested_buyer_role:string|null; recommended_motion:string|null; suppressed:boolean|null };
type ChangeBand = 'act_now'|'review'|'monitor';
type ChangeItem = { id:string; accountId:string; accountName:string; kind:'signal'|'pipeline'; title:string; detail:string; occurredAt:string; confidence?:number|null; materiality:number; band:ChangeBand; reason:string };
function normalizeBand(value:string): ChangeBand { return value === 'act_now' ? 'act_now' : value === 'review' ? 'review' : 'monitor'; }
function relativeDate(value:string) { const days=Math.floor((Date.now()-new Date(value).getTime())/86400000); if(days<=0)return 'Today'; if(days===1)return 'Yesterday'; if(days<7)return `${days} days ago`; return new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric'}); }
function bandLabel(band:ChangeBand) { return band==='act_now'?'Act now':band==='review'?'Review':'Monitor'; }

export default async function Home() {
 const workspace=await requireActiveWorkspace(); const supabase=await createClient(); const recentCutoff=new Date(Date.now()-7*86400000).toISOString();
 const [accountsResult,signalsResult,contactsResult,outreachResult,verifiedCountResult,dueResult,recentSignalsResult,recentPipelineResult]=await Promise.all([
  supabase.from('accounts').select('id,name,domain,opportunity_score,tier,suggested_buyer_role,recommended_motion,suppressed').eq('workspace_id',workspace.id).eq('suppressed',false).order('opportunity_score',{ascending:false,nullsFirst:false}).limit(8),
  supabase.from('signals').select('id,account_id').eq('workspace_id',workspace.id),
  supabase.from('contacts').select('id,account_id,email_verified,is_primary_buyer').eq('workspace_id',workspace.id),
  supabase.from('outreach').select('id,account_id,status').eq('workspace_id',workspace.id),
  supabase.from('accounts').select('id',{count:'exact',head:true}).eq('workspace_id',workspace.id).eq('shopify',true).eq('suppressed',false),
  supabase.from('accounts').select('id,name,next_action,next_action_due,pipeline_stage').eq('workspace_id',workspace.id).eq('suppressed',false).lte('next_action_due',new Date().toISOString().slice(0,10)).not('pipeline_stage','in','(won,lost)').order('next_action_due',{ascending:true}).limit(6),
  supabase.from('signals').select('id,account_id,title,signal_type,observed_at,source_name,confidence,accounts!inner(name,domain,suppressed,opportunity_score)').eq('workspace_id',workspace.id).eq('accounts.suppressed',false).gte('observed_at',recentCutoff).order('observed_at',{ascending:false}).limit(18),
  supabase.from('pipeline_events').select('id,account_id,previous_stage,stage,next_action,next_action_due,recorded_at,accounts!inner(name,domain,suppressed,opportunity_score)').eq('workspace_id',workspace.id).eq('accounts.suppressed',false).gte('recorded_at',recentCutoff).order('recorded_at',{ascending:false}).limit(18),
 ]);
 const coreUnavailable=[accountsResult,signalsResult,contactsResult,outreachResult].some(result=>Boolean(result.error));
 const opportunities=(accountsResult.data??[]) as Account[]; const signals=signalsResult.data??[]; const contacts=contactsResult.data??[]; const outreach=outreachResult.data??[];
 const signalAccounts=new Set(signals.map((s:any)=>s.account_id)); const buyerAccounts=new Set(contacts.filter((c:any)=>c.email_verified&&c.is_primary_buyer).map((c:any)=>c.account_id)); const heldOutreachAccounts=new Set(outreach.filter((i:any)=>['ready','approved'].includes(i.status)).map((i:any)=>i.account_id));
 const qualified=opportunities.filter(a=>typeof a.opportunity_score==='number'); const isReady=(a:Account)=>(a.opportunity_score??0)>=70&&signalAccounts.has(a.id)&&buyerAccounts.has(a.id); const ready=coreUnavailable?[]:qualified.filter(isReady); const topOpportunity=ready[0]??qualified[0]; const topHasEvidence=topOpportunity?signalAccounts.has(topOpportunity.id):false; const topHasBuyer=topOpportunity?buyerAccounts.has(topOpportunity.id):false; const topHasHeldDraft=topOpportunity?heldOutreachAccounts.has(topOpportunity.id):false;
 const recentChanges:ChangeItem[]=[];
 if(!recentSignalsResult.error) for(const signal of recentSignalsResult.data??[]){ const account=Array.isArray(signal.accounts)?signal.accounts[0]:signal.accounts; if(!account)continue; const confidence=typeof signal.confidence==='number'?signal.confidence:Number(signal.confidence??0); const opportunityScore=Number(account.opportunity_score||0); const m=rankObservedChange({signalType:signal.signal_type,confidence,occurredAt:signal.observed_at,opportunityScore,ready:opportunityScore>=70&&buyerAccounts.has(signal.account_id)}); recentChanges.push({id:`signal-${signal.id}`,accountId:signal.account_id,accountName:account.name,kind:'signal',title:signal.title,detail:`${signal.signal_type.replaceAll('_',' ')} observed${signal.source_name?` via ${signal.source_name}`:''}`,occurredAt:signal.observed_at,confidence,materiality:m.materiality,band:normalizeBand(m.band),reason:m.reason}); }
 if(!recentPipelineResult.error) for(const event of recentPipelineResult.data??[]){ const account=Array.isArray(event.accounts)?event.accounts[0]:event.accounts; if(!account)continue; const stageChanged=event.previous_stage!==event.stage; const m=rankPipelineChange({previousStage:event.previous_stage,stage:event.stage,occurredAt:event.recorded_at,opportunityScore:Number(account.opportunity_score||0),nextActionDue:event.next_action_due}); recentChanges.push({id:`pipeline-${event.id}`,accountId:event.account_id,accountName:account.name,kind:'pipeline',title:stageChanged?`${event.previous_stage} → ${event.stage}`:'Next action updated',detail:event.next_action||'Pipeline state changed',occurredAt:event.recorded_at,materiality:m.materiality,band:normalizeBand(m.band),reason:m.reason}); }
 const changeQueue=recentChanges.filter(c=>c.band!=='monitor').sort((a,b)=>b.materiality-a.materiality||new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime()).slice(0,6); const changesUnavailable=Boolean(recentSignalsResult.error&&recentPipelineResult.error); const changesPartial=Boolean(recentSignalsResult.error)!==Boolean(recentPipelineResult.error);
 return <div className="shell"><Sidebar/><main><header><div><div className="eyebrow">Daily command center</div><h1>{workspace.name}</h1><p>Decide what deserves attention today from observed evidence, buyer readiness and pipeline movement.</p></div><Link className="primary" href="/discover">Run discovery</Link></header>
 {coreUnavailable?<section className="panel noticePanel"><strong>Decision readiness is partially unavailable</strong><p>One or more evidence, buyer or outreach reads did not complete. The product will not infer readiness from incomplete data. Visible account scores remain useful for research, but readiness is withheld until the underlying reads recover.</p></section>:null}
 <section className="panel"><div className="panelHead"><div><span className="eyebrow">Decision queue · last 7 days</span><h2>What changed enough to matter</h2></div><Link href="/accounts">Explore opportunities</Link></div>{changesPartial?<div className="partialState"><strong>Partial change intelligence</strong><span>One activity source is unavailable, so this queue may be incomplete.</span></div>:null}{changesUnavailable?<div className="emptyState"><strong>Change intelligence is temporarily unavailable.</strong><p>Your opportunity and pipeline data remain intact. This queue is withheld rather than reconstructed from incomplete reads.</p></div>:changeQueue.length?<div className="evidenceList">{changeQueue.map(change=><Link className="evidenceItem changeDecision" href={`/accounts/${change.accountId}`} key={change.id}><div><span className="eyebrow">{bandLabel(change.band)} · {change.kind==='signal'?'Observed signal':'Pipeline movement'} · {relativeDate(change.occurredAt)}</span><strong>{change.accountName} · {change.title}</strong><small>{change.detail}{change.kind==='signal'&&change.confidence!=null?` · ${Math.round(change.confidence*100)}% confidence`:''}</small><p className="changeReason">{change.reason}</p></div><div className="changeMateriality"><span>Materiality</span><strong>{change.materiality}</strong><small>Inspect →</small></div></Link>)}</div>:<div className="emptyState"><strong>No decision-changing activity in the last 7 days.</strong><p>Low-materiality changes stay out of your way. This queue appears when observed evidence or pipeline movement is strong enough to deserve operator attention.</p></div>}</section>
 <section className="panel"><div className="panelHead"><div><span className="eyebrow">Next actions</span><h2>Due for attention</h2></div><Link href="/pipeline">Open pipeline</Link></div>{dueResult.error?<div className="emptyState"><strong>Next actions are temporarily unavailable</strong><p>Pipeline records remain intact. This section will not substitute guessed due work.</p></div>:dueResult.data?.length?<div className="evidenceList">{dueResult.data.map(item=><div className="evidenceItem" key={item.id}><div><strong>{item.name}</strong><small>{item.next_action} · Due {item.next_action_due}</small></div><Link href={`/accounts/${item.id}`}>Open opportunity →</Link></div>)}</div>:<div className="emptyState"><strong>Nothing is overdue today</strong><p>Record the next committed step in Pipeline so the Command Center can bring it back at the right time.</p></div>}</section>
 <section className="metrics"><div className="card"><span>Ready in priority queue</span><strong>{coreUnavailable?'—':ready.length}</strong><small>{coreUnavailable?'Withheld while readiness inputs recover':'70+ score, observed evidence and a verified primary buyer'}</small></div><div className="card"><span>Verified Shopify</span><strong>{verifiedCountResult.error?'—':verifiedCountResult.count??0}</strong><small>{verifiedCountResult.error?'Count temporarily unavailable':'Unsuppressed workspace storefronts'}</small></div><div className="card"><span>Evidence signals</span><strong>{signalsResult.error?'—':signals.length}</strong><small>{signalsResult.error?'Evidence read temporarily unavailable':'Observed reasons to investigate'}</small></div></section>
 {topOpportunity?<section className="panel commandSpotlight"><div className="panelHead"><div><span className="eyebrow">{!coreUnavailable&&isReady(topOpportunity)?'Start here':'Research next'}</span><h2>{topOpportunity.name}</h2><p>{topOpportunity.domain}</p></div><ScoreRing score={topOpportunity.opportunity_score??0}/></div><div className="spotlightNarrative"><div><span className="eyebrow">Why it deserves attention</span><h3>{topHasEvidence?'Observed evidence is attached to this account.':'The account fits the model, but still needs an observed reason to act.'}</h3><p>{topHasBuyer?'A verified primary buyer is available.':'Buyer readiness is not complete yet.'}</p></div><div className="spotlightAction"><span className="eyebrow">Next best action</span><strong>{coreUnavailable?'Review once readiness recovers':!topHasEvidence?'Build evidence':!topHasBuyer?'Research and verify buyer':topHasHeldDraft?'Review held draft':isReady(topOpportunity)?'Prepare held draft':'Keep researching'}</strong><small>{topOpportunity.recommended_motion||'Evidence-first motion'}</small></div></div><div className="readinessStrip"><span className={topHasEvidence?'readyCheck':'holdCheck'}>Evidence {topHasEvidence?'ready':'needed'}</span><span className={topHasBuyer?'readyCheck':'holdCheck'}>Buyer {topHasBuyer?'verified':'needed'}</span><span className={topHasHeldDraft?'readyCheck':'holdCheck'}>Draft {topHasHeldDraft?'held':'not prepared'}</span></div><Link className="primary inlineAction" href={`/accounts/${topOpportunity.id}`}>Open opportunity intelligence</Link></section>:!accountsResult.error?<section className="panel emptyState"><span className="eyebrow">Your first signal</span><h2>No qualified opportunities yet.</h2><p>This command center only shows real workspace data. Run discovery to find and verify commerce accounts; nothing here is padded with demo prospects or invented activity.</p><Link className="primary inlineAction" href="/discover">Open discovery</Link></section>:null}
 {opportunities.length?<section id="opportunities" className="panel"><div className="panelHead"><div><span className="eyebrow">Priority bench</span><h2>Strong candidates behind the spotlight</h2></div><Link href="/accounts">View all accounts</Link></div><div className="priorityCards">{opportunities.map(account=><Link href={`/accounts/${account.id}`} className="priorityCard" key={account.id}><div className="priorityScore"><ScoreRing score={account.opportunity_score??0}/></div><div className="priorityIdentity"><strong>{account.name}</strong><small>{account.domain}</small><span className="pill">{coreUnavailable?'Readiness pending':isReady(account)?'Ready':signalAccounts.has(account.id)?'Research buyer':'Build evidence'}</span></div><div className="priorityMotion"><span>Motion</span><strong>{account.recommended_motion||'Review evidence'}</strong><small>{account.suggested_buyer_role||'Buyer research first'}</small></div><span className="priorityArrow">Inspect →</span></Link>)}</div></section>:null}
 <section className="split"><div className="panel"><span className="eyebrow">Evidence rule</span><h2>No reason, no outreach.</h2><p>Every recommendation must trace back to observed evidence. A technology match alone is context, not proof of service need.</p></div><div className="panel"><span className="eyebrow">Human control</span><h2>Decision support, not autopilot.</h2><p>Research and drafting can accelerate the work. External outreach remains behind explicit human review and approval.</p></div></section></main></div>;
}
