import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Sidebar } from '../../../components/Sidebar';
import { ScoreRing } from '../../../components/ScoreRing';
import { createClient } from '../../../lib/supabase/server';
import { requireActiveWorkspace } from '../../../lib/workspaces/session';
import { prepareOutreach, researchBuyers } from './actions';

export const dynamic = 'force-dynamic';

function humanize(value:string){return value.replace(/[_-]/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase())}
function when(value:string|undefined|null){if(!value)return 'Date unavailable';const date=new Date(value);return Number.isNaN(date.getTime())?'Date unavailable':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function movementLabel(delta:number|null){if(delta===null)return 'Baseline recorded';if(delta===0)return 'No score change';return `${delta>0?'+':''}${delta} points`;}
function componentMovementLabel(previous:number|null,current:number){if(previous===null)return 'Baseline';const delta=current-previous;if(delta===0)return 'Unchanged';return `${delta>0?'+':''}${delta} since prior receipt`;}

export default async function AccountPage({ params, searchParams }: { params: Promise<{id:string}>, searchParams: Promise<Record<string,string|undefined>> }) {
  const [{ id }, query, workspace] = await Promise.all([params, searchParams, requireActiveWorkspace()]);
  const supabase = await createClient();
  const [accountResult, signalsResult, contactsResult, pipelineResult, scoringHistoryResult] = await Promise.all([
    supabase.from('accounts').select('*').eq('workspace_id', workspace.id).eq('id', id).maybeSingle(),
    supabase.from('signals').select('id,signal_type,title,source_name,source_url,observed_at,confidence,evidence').eq('workspace_id', workspace.id).eq('account_id', id).order('observed_at', { ascending:false }).limit(20),
    supabase.from('contacts').select('*').eq('workspace_id', workspace.id).eq('account_id', id).order('is_primary_buyer', { ascending:false }).order('buyer_score', { ascending:false, nullsFirst:false }),
    supabase.from('pipeline_events').select('id,previous_stage,stage,next_action,next_action_due,revision,recorded_at').eq('workspace_id',workspace.id).eq('account_id',id).order('recorded_at',{ascending:false}).limit(12),
    supabase.from('scoring_snapshots').select('id,scoring_contract_version,fit_score,need_score,intent_score,opportunity_score,tier,evidence_confidence,explanation,evidence_refs,created_at').eq('workspace_id',workspace.id).eq('account_id',id).order('created_at',{ascending:false}).limit(6),
  ]);
  const account:any = accountResult.data;
  if (accountResult.error || !account) notFound();
  const signals:any[] = signalsResult.data || [];
  const contacts:any[] = contactsResult.data || [];
  const pipelineEvents:any[] = pipelineResult.data || [];
  const intelligencePartial = Boolean(signalsResult.error || contactsResult.error);
  const timelinePartial = Boolean(signalsResult.error || pipelineResult.error);
  const primary = contacts.find((contact:any) => contact.is_primary_buyer);
  const verifiedBuyer = !contactsResult.error && Boolean(primary?.email_verified);
  const hasEvidence = !signalsResult.error && Boolean(signals.length);
  const score = Number(account.opportunity_score || 0);
  const ready = !intelligencePartial && score >= 70 && hasEvidence && verifiedBuyer;
  const canOperate = ['owner','admin','member'].includes(workspace.role);
  const need = account.qualification_inputs?.need || {};
  const topNeed = Object.entries(need).filter(([,v])=>Number(v)>0).sort((a,b)=>Number(b[1])-Number(a[1]))[0];
  const topSignal = signals[0];
  const nextAction = intelligencePartial ? 'Restore intelligence' : !hasEvidence ? 'Build evidence' : !primary ? 'Research the buyer' : !verifiedBuyer ? 'Verify the buyer' : ready ? 'Prepare outreach' : 'Keep researching';
  const whyNow = signalsResult.error ? 'Evidence is temporarily unavailable; timing is withheld until the evidence read succeeds.' : topSignal?.title || 'No observed trigger has been persisted yet.';
  const thesis = intelligencePartial ? `${account.name} cannot be safely assessed for outreach readiness because part of its evidence or buyer intelligence is unavailable.` : hasEvidence ? `${account.name} has observed evidence supporting a ${account.recommended_motion || 'research-first'} motion${topNeed ? `, with ${humanize(topNeed[0])} as the strongest modeled need` : ''}.` : `${account.name} fits the account model, but there is not yet enough observed evidence to justify outreach.`;
  const scoringHistory = scoringHistoryResult.error ? [] : (scoringHistoryResult.data || []);
  const currentScoreReceipt:any = scoringHistory[0]; const previousScoreReceipt:any = scoringHistory[1];
  const scoreDelta:number|null = currentScoreReceipt && previousScoreReceipt ? Number(currentScoreReceipt.opportunity_score)-Number(previousScoreReceipt.opportunity_score) : null;
  const scoreComponents:{label:string;current:number;previous:number|null}[] = currentScoreReceipt ? [{label:'Fit',current:Number(currentScoreReceipt.fit_score),previous:previousScoreReceipt?Number(previousScoreReceipt.fit_score):null},{label:'Need',current:Number(currentScoreReceipt.need_score),previous:previousScoreReceipt?Number(previousScoreReceipt.need_score):null},{label:'Intent',current:Number(currentScoreReceipt.intent_score),previous:previousScoreReceipt?Number(previousScoreReceipt.intent_score):null}] : [];
  const strongestMovement = scoreComponents.filter(c=>c.previous!==null).map(c=>({...c,delta:c.current-(c.previous as number)})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta))[0];

  return <div className="shell"><Sidebar/><main><Link className="back" href="/">← Daily Command Center</Link>
    <header className="opportunityHero"><div><div className="eyebrow">Opportunity intelligence</div><h1>{account.name}</h1><p>{account.domain} · {[account.country,account.industry].filter(Boolean).join(' · ')}</p><div className="tags"><span>{account.tier || 'Un-tiered'}</span><span>{account.recommended_motion || 'research-first'}</span><span>{intelligencePartial ? 'Readiness unavailable' : ready ? 'Ready for review' : 'Research in progress'}</span></div></div><ScoreRing score={score}/></header>
    {query.error ? <section className="panel noticePanel"><strong>Action could not complete</strong><p>{query.error}</p></section> : null}{query.notice ? <section className="panel noticePanel"><strong>{query.notice}</strong></section> : null}
    {intelligencePartial ? <section className="panel noticePanel"><div className="eyebrow">Partial intelligence</div><h2>Readiness is withheld</h2><p>Evidence or buyer data could not be read completely. The stored score remains visible for context, but the product will not infer outreach readiness from partial data.</p></section> : null}
    <section className="opportunityLead"><div className="panel thesisPanel"><span className="eyebrow">Commercial thesis</span><h2>{thesis}</h2><p className="whyNow"><strong>Why now</strong><br/>{whyNow}</p></div><div className="panel actionPanel"><span className="eyebrow">Next best action</span><h2>{nextAction}</h2><p>{intelligencePartial ? 'No outreach action is offered until the missing intelligence is available again.' : ready ? 'Evidence and a verified primary buyer are present. Prepare an exact draft for the held outbox; a human must review it before any external action.' : 'The system will not treat this account as outreach-ready until the missing proof is resolved.'}</p>{!intelligencePartial && !primary && canOperate ? <form action={researchBuyers}><input type="hidden" name="accountId" value={account.id}/><button className="primary" type="submit">Research buyers</button></form> : null}{ready && canOperate ? <form action={prepareOutreach}><input type="hidden" name="accountId" value={account.id}/><button className="primary" type="submit">Prepare held draft</button><small>Creates a revision-bound review item. Does not send.</small></form> : null}</div></section>
    <section className="metrics opportunityMetrics"><div className="card"><span>Fit</span><strong>{account.fit_score ?? '—'}</strong><small>ICP alignment</small></div><div className="card"><span>Need</span><strong>{account.need_score ?? '—'}</strong><small>Evidence-backed opportunity</small></div><div className="card"><span>Intent</span><strong>{account.intent_score ?? '—'}</strong><small>Timing strength</small></div><div className="card"><span>Readiness</span><strong>{intelligencePartial ? 'Unknown' : ready ? 'Ready' : 'Hold'}</strong><small>{intelligencePartial ? 'Partial intelligence · action withheld' : `${hasEvidence ? 'Evidence ✓' : 'Evidence needed'} · ${verifiedBuyer ? 'Buyer ✓' : 'Buyer needed'}`}</small></div></section>
    <section className="panel scoreStory"><div className="panelHead"><div><span className="eyebrow">Score intelligence</span><h2>Why the score is {score}</h2></div>{currentScoreReceipt ? <span className="pill">{currentScoreReceipt.scoring_contract_version}</span> : null}</div>{scoringHistoryResult.error ? <div className="emptyState"><strong>Score history is temporarily unavailable</strong><p>The current opportunity score remains visible, but this explanation is withheld rather than reconstructed without its immutable receipt.</p></div> : currentScoreReceipt ? <><div className="scoreMovement"><div><span className="eyebrow">Movement</span><strong>{movementLabel(scoreDelta)}</strong><small>{scoreDelta===null?`First versioned receipt · ${when(currentScoreReceipt.created_at)}`:`Since ${when(previousScoreReceipt.created_at)}`}</small></div><div><span className="eyebrow">Strongest driver</span><strong>{strongestMovement&&strongestMovement.delta!==0?`${strongestMovement.label} ${strongestMovement.delta>0?'+':''}${strongestMovement.delta}`:'No component shift'}</strong><small>{strongestMovement?`${strongestMovement.previous} → ${strongestMovement.current}`:'Waiting for a second scoring receipt'}</small></div><div><span className="eyebrow">Evidence confidence</span><strong>{Math.round(Number(currentScoreReceipt.evidence_confidence||0)*100)}%</strong><small>{Array.isArray(currentScoreReceipt.evidence_refs)?`${currentScoreReceipt.evidence_refs.length} referenced evidence items`:'Receipt preserved'}</small></div></div><div className="needStack">{scoreComponents.map(c=><div key={c.label}><span>{c.label}<small>{componentMovementLabel(c.previous,c.current)}</small></span><strong>{c.current}</strong></div>)}</div><p><small>Deterministic scoring receipt · recorded {when(currentScoreReceipt.created_at)}. This explains stored scoring state; it does not invent a causal claim beyond the recorded inputs and evidence.</small></p></> : <div className="emptyState"><strong>No versioned scoring receipt yet</strong><p>This account predates scoring history or has not been re-qualified. The current score is shown above, but the product will not fabricate historical reasoning.</p></div>}</section>
    <section className="split"><div className="panel"><span className="eyebrow">Buyer readiness</span>{contactsResult.error ? <><h2>Buyer intelligence unavailable</h2><p>The product will not assume a missing buyer or verification state while this read is incomplete.</p></> : primary ? <><h2>{primary.full_name||[primary.first_name,primary.last_name].filter(Boolean).join(' ')}</h2><p>{primary.title||account.suggested_buyer_role||'Recommended buyer'}</p><div className="readinessLine"><span className="pill">{primary.email_verified?'Verified email':'Verification required'}</span><small>Buyer score {primary.buyer_score??'—'} · {primary.verification_source||primary.provider||'source pending'}</small></div></> : <><h2>{account.suggested_buyer_role||'Buyer research required'}</h2><p>No named primary buyer is attached yet. Research ranks candidates before enrichment spend.</p>{canOperate?<form action={researchBuyers}><input type="hidden" name="accountId" value={account.id}/><button className="primary" type="submit">Research buyers</button></form>:<p><small>An operator can run buyer research; viewers remain read-only.</small></p>}</>}</div><div className="panel"><span className="eyebrow">Need model</span><h2>What the evidence suggests</h2>{Object.entries(need).filter(([,v])=>Number(v)>0).length?<div className="needStack">{Object.entries(need).filter(([,v])=>Number(v)>0).sort((a,b)=>Number(b[1])-Number(a[1])).map(([key,value])=><div key={key}><span>{humanize(key)}</span><strong>{Math.round(Number(value)*100)}%</strong></div>)}</div>:<p>No need dimensions have enough evidence yet.</p>}</div></section>
    <section className="panel"><div className="panelHead"><div><span className="eyebrow">What changed</span><h2>Opportunity timeline</h2></div><span className="pill">{timelinePartial?'Partial':`${signals.length+pipelineEvents.length} recorded events`}</span></div>{timelinePartial?<div className="emptyState"><strong>Timeline is partially unavailable</strong><p>One or more event sources could not be read. The product is withholding a complete-history claim until the read succeeds.</p></div>:(signals.length||pipelineEvents.length)?<div className="evidenceList">{[...signals.map((s:any)=>({id:`signal-${s.id}`,at:s.observed_at,title:s.title,detail:`${humanize(s.signal_type)} · ${s.source_name||'Persisted source'} · ${Math.round(Number(s.confidence||0)*100)}% confidence`,url:s.source_url})),...pipelineEvents.map((e:any)=>({id:`pipeline-${e.id}`,at:e.recorded_at,title:e.previous_stage===e.stage?`Next action updated in ${humanize(e.stage)}`:`Pipeline moved ${humanize(e.previous_stage)} → ${humanize(e.stage)}`,detail:e.next_action?`${e.next_action}${e.next_action_due?` · Due ${when(e.next_action_due)}`:''}`:`Revision ${e.revision}`,url:null}))].sort((a,b)=>new Date(b.at||0).getTime()-new Date(a.at||0).getTime()).slice(0,12).map((e:any)=><article className="evidenceItem" key={e.id}><div><strong>{e.title}</strong><small>{when(e.at)} · {e.detail}</small></div>{e.url?<a href={e.url} target="_blank" rel="noreferrer">Inspect source ↗</a>:<span className="pill">Recorded change</span>}</article>)}</div>:<div className="emptyState"><strong>No material changes recorded yet</strong><p>New evidence and operator pipeline movement will appear here instead of being flattened into current-state fields.</p></div>}</section>
    <section className="panel"><div className="panelHead"><div><span className="eyebrow">Evidence receipts</span><h2>Why the system believes this</h2></div><span className="pill">{signalsResult.error?'Unavailable':`${signals.length} observed`}</span></div>{signalsResult.error?<div className="emptyState"><strong>Evidence receipts are temporarily unavailable</strong><p>No readiness or evidence-count conclusion is drawn from this failed read.</p></div>:signals.length?<div className="evidenceList">{signals.map((s:any)=><article key={s.id} className="evidenceItem"><div><strong>{s.title}</strong><small>{when(s.observed_at)} · {humanize(s.signal_type)} · {s.source_name||'source'} · {Math.round(Number(s.confidence||0)*100)}% confidence</small></div>{s.source_url?<a href={s.source_url} target="_blank" rel="noreferrer">Inspect source ↗</a>:<span className="pill">Persisted evidence</span>}</article>)}</div>:<div className="emptyState"><strong>No observed evidence yet</strong><p>Technology fit or account score alone is not treated as proof of need.</p></div>}</section>
    <section className="panel"><div className="panelHead"><div><span className="eyebrow">Buyer bench</span><h2>Ranked people</h2></div></div>{contactsResult.error?<div className="emptyState"><strong>Buyer bench is temporarily unavailable</strong><p>Candidate and verification states are withheld until the contact read succeeds.</p></div>:contacts.length?<div className="buyerCards">{contacts.map((c:any)=><article className="buyerCard" key={c.id}><div><strong>{c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')}</strong><small>{c.title||'Role unknown'}</small></div><div><span className="pill">{c.email_verified?'verified':c.verification_status||'candidate'}</span><small>Score {c.buyer_score??'—'}</small></div></article>)}</div>:<div className="emptyState"><strong>No buyer candidates yet</strong><p>Buyer research has not been run for this account.</p></div>}</section>
  </main></div>;
}