import { Sidebar } from '../../components/Sidebar';
import { createClient } from '../../lib/supabase/server';
import { requireActiveWorkspace } from '../../lib/workspaces/session';
import { updateWorkspaceSettings } from './actions';
import { suppressDomain, liftSuppression } from './suppression-actions';

const serviceOptions=['Shopify development','CRO','UX/UI','Klaviyo / retention','Analytics','Subscriptions','QA','B2B'];
const industryOptions=['beauty','wellness','supplements','apparel','food-beverage','fitness','pet','home'];
export const dynamic='force-dynamic';

export default async function SettingsPage({searchParams}:{searchParams:Promise<{notice?:string,error?:string}>}) {
 const workspace=await requireActiveWorkspace(); const supabase=await createClient(); const params=await searchParams;
 const [configResult,suppressionResult,accountsResult,governanceResult]=await Promise.all([
  supabase.from('workspace_sales_config').select('*').eq('workspace_id',workspace.id).maybeSingle(),
  supabase.from('suppression_entries').select('id,scope,normalized_value,reason,source,created_at,lifted_at,lift_reason').eq('workspace_id',workspace.id).order('created_at',{ascending:false}).limit(50),
  supabase.from('accounts').select('id,name,domain').eq('workspace_id',workspace.id).order('name').limit(200),
  supabase.from('data_governance_policies').select('default_retention_days,contact_retention_days,evidence_retention_days,purpose,updated_at').eq('workspace_id',workspace.id).maybeSingle()
 ]);
 const data:any=configResult.data; const suppressions:any[]=suppressionResult.data||[]; const accounts:any[]=accountsResult.data||[]; const governance:any=governanceResult.data;
 const configAvailable=!configResult.error&&Boolean(data); const services=new Set(configAvailable?(data.services||[]).map(String):[]),countries=new Set(configAvailable?(data.target_countries||[]).map(String):[]),industries=new Set(configAvailable?(data.target_industries||[]).map(String):[]); const outreach=configAvailable?(data.outreach_rules||{}):{};
 const canEdit=['owner','admin'].includes(workspace.role); const active=suppressions.filter(s=>!s.lifted_at),history=suppressions.filter(s=>s.lifted_at); const suppressionAvailable=!suppressionResult.error; const accountContextAvailable=!accountsResult.error;
 return <div className="shell"><Sidebar/><main>
  <header><div><div className="eyebrow">Workspace settings</div><h1>{workspace.name}</h1><p>Control targeting, operating policy and the safety boundaries around commercial outreach.</p></div></header>
  {params.notice&&<section className="panel noticePanel"><strong>Saved</strong><p>{params.notice}</p></section>}{params.error&&<section className="panel noticePanel"><strong>Could not complete that action</strong><p>{params.error}</p></section>}

  <section className="panel"><div className="panelHead"><div><div className="eyebrow">Data governance</div><h2>Purpose and retention posture</h2></div><span className="pill">Policy controls</span></div>{governanceResult.error?<div className="emptyState"><strong>Governance policy is temporarily unavailable</strong><p>Retention and purpose values are withheld rather than replaced with guessed defaults. This does not change suppression or human-approval enforcement.</p></div>:governance?<><p>{governance.purpose}</p><div className="metrics" style={{marginTop:18,marginBottom:8}}><div className="card"><span>Business data</span><strong>{governance.default_retention_days}</strong><small>days · product policy</small></div><div className="card"><span>Professional contacts</span><strong>{governance.contact_retention_days}</strong><small>days · product policy</small></div><div className="card"><span>Evidence</span><strong>{governance.evidence_retention_days}</strong><small>days · product policy</small></div><div className="card"><span>Legal status</span><strong>Review</strong><small>Not a compliance claim</small></div></div><p><small>These are workspace product-policy values. Jurisdiction-specific retention and outreach requirements still require validated policy/legal review before production enforcement.</small></p></>:<div className="emptyState"><strong>No governance policy has been configured</strong><p>The system will not present retention defaults as an approved legal policy. An owner/admin should establish and validate workspace policy before production-scale collection.</p></div>}</section>

  {configAvailable?<form action={updateWorkspaceSettings} className="panel" style={{display:'grid',gap:24}}><div><div className="eyebrow">Commercial configuration</div><h2>Who this workspace should pursue</h2></div>
   <fieldset disabled={!canEdit}><legend>Services</legend><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginTop:10}}>{serviceOptions.map(s=><label key={s}><input type="checkbox" name="services" value={s} defaultChecked={services.has(s)}/> {s}</label>)}</div></fieldset>
   <fieldset disabled={!canEdit}><legend>Target countries</legend><div style={{display:'flex',gap:16,marginTop:10}}>{['US','CA','GB'].map(c=><label key={c}><input type="checkbox" name="countries" value={c} defaultChecked={countries.has(c)}/> {c}</label>)}</div></fieldset>
   <fieldset disabled={!canEdit}><legend>Preferred verticals</legend><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginTop:10}}>{industryOptions.map(i=><label key={i}><input type="checkbox" name="industries" value={i} defaultChecked={industries.has(i)}/> {i}</label>)}</div></fieldset>
   <fieldset disabled={!canEdit}><legend>Outreach safety policy</legend><p>Source-backed reasons, verified professional email and human approval are always required. Autonomous sending is disabled.</p><label>Collection purpose<input name="collectionPurpose" style={{display:"block",width:"100%",marginTop:6,padding:12}} required maxLength={1000} defaultValue={governance?.purpose || 'B2B commerce revenue intelligence and operator-approved outreach'}/></label><p>Only record a region basis after your workspace has reviewed it. A saved basis permits human review of qualifying drafts; it does not establish legal compliance or enable sending.</p><div style={{display:'grid',gap:16}}>{['US','CA','GB','EU'].map(region=><div key={region}><label>{region} policy reference<input name={`policyReference_${region}`} style={{display:"block",width:"100%",marginTop:6,padding:12}} maxLength={500} defaultValue={outreach.regionPolicyBasis?.[region]?.reference || ''} placeholder="Reviewed policy document or reference"/></label><label><input type="checkbox" name={`policyReviewed_${region}`} defaultChecked={outreach.regionPolicyBasis?.[region]?.status==='verified'}/> Workspace has reviewed this region basis</label></div>)}</div></fieldset>
   {canEdit?<button className="primary" type="submit">Save workspace settings</button>:<p>Workspace policy is read-only for your role.</p>}
  </form>:<section className="panel noticePanel"><div className="eyebrow">Configuration unavailable</div><h2>Commercial settings could not be loaded</h2><p>Targeting and outreach settings are withheld rather than rendering unchecked controls that could be mistaken for the saved policy. Safety enforcement remains server-side.</p></section>}

  <section style={{marginTop:28}}><div className="eyebrow">Outreach safety</div><h2 style={{marginBottom:6}}>Suppression ledger</h2><p style={{maxWidth:720}}>A durable stop list checked again at draft creation and approval. Lifting a suppression preserves its audit history; it does not send anything.</p>
   {!suppressionAvailable?<section className="panel noticePanel" style={{marginTop:16}}><strong>Suppression ledger could not be read</strong><p>The product will not claim the ledger is clear. Draft and approval enforcement remains at the database boundary.</p></section>:<>
   {canEdit&&accountContextAvailable&&<form action={suppressDomain} className="panel" style={{display:'grid',gap:14,marginTop:16}}><div><strong>Suppress a business domain</strong><p style={{margin:'4px 0 0'}}>Use for opt-outs, legal/policy holds, relationship conflicts or any business you do not want contacted.</p></div><select name="accountId" required defaultValue=""><option value="" disabled>Select account context</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.domain}</option>)}</select><input name="domain" placeholder="example.com" required/><input name="reason" placeholder="Reason for suppression" maxLength={500} required/><button className="primary" type="submit">Add to suppression ledger</button></form>}
   {canEdit&&!accountContextAvailable?<section className="panel noticePanel" style={{marginTop:16}}><strong>Account context is temporarily unavailable</strong><p>New suppression entry controls are withheld until account context can be read. Existing suppressions remain enforced.</p></section>:null}
   <div style={{display:'grid',gap:12,marginTop:16}}>{active.length===0?<div className="panel"><strong>No active ledger entries</strong><p>The workspace suppression ledger currently has no active entries. Account-level legacy suppression and all other approval guardrails remain independently enforced.</p></div>:active.map(s=><article className="panel" key={s.id}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="eyebrow">{s.scope} · active</div><h3 style={{margin:'6px 0'}}>{s.normalized_value||'Scoped record'}</h3><p style={{margin:0}}>{s.reason}</p><small>{s.source} · {new Date(s.created_at).toLocaleDateString()}</small></div>{canEdit&&<form action={liftSuppression} style={{display:'grid',gap:8,minWidth:260}}><input type="hidden" name="suppressionId" value={s.id}/><input name="liftReason" placeholder="Why is it safe to lift?" maxLength={500} required/><button type="submit">Lift suppression</button></form>}</div></article>)}</div>
   {history.length>0&&<details className="panel" style={{marginTop:16}}><summary><strong>Audit history · {history.length} lifted</strong></summary><div style={{display:'grid',gap:12,marginTop:16}}>{history.map(s=><div key={s.id}><strong>{s.normalized_value||s.scope}</strong><p style={{margin:'3px 0'}}>Suppressed: {s.reason}</p><small>Lifted: {s.lift_reason||'reason retained in audit record'}</small></div>)}</div></details>}</>}
  </section>
 </main></div>;
}
