-- Run only on isolated staging via SQL tooling. Entire transaction rolls back.
begin;
insert into auth.users(id,aud,role,email) values('90000000-0000-4000-8000-000000000001','authenticated','authenticated','acceptance-owner@example.invalid'),('90000000-0000-4000-8000-000000000002','authenticated','authenticated','acceptance-other@example.invalid');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select set_config('test.workspace',create_workspace_with_owner('Acceptance A','acceptance-a-20261009','["CRO"]','{US}','{beauty}')::text,true);
select set_config('request.jwt.claims','{"sub":"90000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select set_config('test.other_workspace',create_workspace_with_owner('Acceptance B','acceptance-b-20261009','[]','{CA}','{}')::text,true);
insert into accounts(id,workspace_id,domain,name) values('90000000-0000-4000-8000-000000000007',current_setting('test.other_workspace')::uuid,'other.example.invalid','Other synthetic account');
insert into contacts(workspace_id,account_id,email) values(current_setting('test.other_workspace')::uuid,'90000000-0000-4000-8000-000000000007','other@example.invalid');
insert into signals(workspace_id,account_id,signal_type,title,source_url,observed_at) values(current_setting('test.other_workspace')::uuid,'90000000-0000-4000-8000-000000000007','acceptance','Other synthetic signal','https://example.invalid',now());
insert into proof_points(workspace_id,client_name,approved_claim) values(current_setting('test.other_workspace')::uuid,'Other fixture','Unapproved synthetic proof');
insert into outreach(workspace_id,account_id,body) values(current_setting('test.other_workspace')::uuid,'90000000-0000-4000-8000-000000000007','Other synthetic draft');
insert into durable_jobs(workspace_id,job_type,idempotency_key) values(current_setting('test.other_workspace')::uuid,'discovery','other-acceptance');
select set_config('request.jwt.claims','{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into accounts(id,workspace_id,domain,name,country) values('90000000-0000-4000-8000-000000000003',current_setting('test.workspace')::uuid,'acceptance.example.invalid','Synthetic acceptance account','US');
insert into contacts(id,workspace_id,account_id,email,email_verified) values('90000000-0000-4000-8000-000000000004',current_setting('test.workspace')::uuid,'90000000-0000-4000-8000-000000000003','buyer@example.invalid',true);
insert into signals(id,workspace_id,account_id,signal_type,title,source_url,observed_at) values('90000000-0000-4000-8000-000000000005',current_setting('test.workspace')::uuid,'90000000-0000-4000-8000-000000000003','acceptance','Synthetic signal','https://example.invalid',now());
insert into source_provenance(workspace_id,entity_type,entity_id,provider,source_class,collection_purpose,license_status) values(current_setting('test.workspace')::uuid,'signal','90000000-0000-4000-8000-000000000005','synthetic','manual','Synthetic acceptance','verified');
insert into data_governance_policies(workspace_id,purpose) values(current_setting('test.workspace')::uuid,'Synthetic acceptance');
update workspace_sales_config set outreach_rules='{"regionPolicyBasis":{"US":{"status":"verified","reference":"Synthetic acceptance only"}}}' where workspace_id=current_setting('test.workspace')::uuid;
select set_config('test.outreach' ,outreach_id::text,true),set_config('test.revision',revision_id::text,true) from create_held_outreach_revision('90000000-0000-4000-8000-000000000003','90000000-0000-4000-8000-000000000004','Synthetic','Synthetic test body','research','Synthetic reason','[{"id":"90000000-0000-4000-8000-000000000005"}]','[]','{"email":"buyer@example.invalid","emailVerified":true}','{"humanApprovalRequired":true,"autonomousSendEnabled":false,"suppressed":false}','acceptance-hash');
-- Rollback-only staging acceptance; no real people or provider requests.
create temporary table acceptance_results(check_name text primary key, passed boolean not null);
grant all on acceptance_results to authenticated;
create function pg_temp.assert_ok(condition boolean,label text) returns void language plpgsql as $$ begin
  if condition is not true then raise exception 'Acceptance failure: %',label; end if;
  insert into acceptance_results values(label,true);
end; $$;
create function pg_temp.expect_error(statement text, expected text,label text) returns void language plpgsql as $$
declare message text;
begin
  begin execute statement; exception when others then message:=sqlerrm; end;
  if message is null or position(expected in message)=0 then raise exception 'Acceptance failure: %, expected %, got %',label,expected,message; end if;
  insert into acceptance_results values(label,true);
end; $$;
select pg_temp.assert_ok((select count(*)=1 from workspaces),'Owner sees only own workspace');
select pg_temp.assert_ok((select role='owner' from workspace_members where user_id=auth.uid()),'Onboarding created owner membership');
select pg_temp.assert_ok((select services='["CRO"]'::jsonb from workspace_sales_config where workspace_id=current_setting('test.workspace')::uuid),'Onboarding stored services');
do $$ declare t text; n bigint; begin
  for t in select table_name from information_schema.columns where table_schema='public' and column_name='workspace_id' loop
    execute format('select count(*) from public.%I where workspace_id=$1',t) into n using current_setting('test.other_workspace')::uuid;
    perform pg_temp.assert_ok(n=0,'Tenant isolation: '||t);
  end loop;
end; $$;
select pg_temp.expect_error(format('insert into accounts(workspace_id,domain,name) values(%L,%L,%L)',current_setting('test.other_workspace'),'cross.example.invalid','Cross tenant'),'row-level security','Cross-tenant insert denied');
select pg_temp.assert_ok(update_native_pipeline(current_setting('test.workspace')::uuid,'90000000-0000-4000-8000-000000000003',0,'qualified','Synthetic review',null)=1,'Owner pipeline and audit RPC');
select pg_temp.expect_error(format('select update_native_pipeline(%L,%L,0,%L,%L,null)',current_setting('test.workspace'),'90000000-0000-4000-8000-000000000003','qualified','stale'),'pipeline changed','Stale pipeline rejected');
select pg_temp.expect_error(format('update outreach set status=%L,approved_revision_id=current_revision_id,approved_by=%L where id=%L','approved',auth.uid(),current_setting('test.outreach')),'exact owner/admin approval','Direct approval-state bypass denied');
select pg_temp.expect_error(format('update outreach set status=%L where id=%L','sent',current_setting('test.outreach')),'outbound sending disabled','Direct send state denied');
select pg_temp.assert_ok((select policy_receipt->>'decision'='eligible_for_human_review' from outreach_revisions where id=current_setting('test.revision')::uuid),'Policy receipt derived from stored inputs');
select set_config('test.suppression',add_suppression('account','90000000-0000-4000-8000-000000000003',null,null,'Synthetic stop','acceptance')::text,true);
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'suppressed outreach','Suppression blocks review RPC');
select pg_temp.expect_error(format('insert into outreach_approvals(workspace_id,outreach_id,revision_id,decision,decided_by) values(%L,%L,%L,%L,%L)',current_setting('test.workspace'),current_setting('test.outreach'),current_setting('test.revision'),'approved',auth.uid()),'suppressed outreach','Suppression blocks direct approval insert');
select pg_temp.assert_ok(review_outreach_revision(current_setting('test.outreach')::uuid,current_setting('test.revision')::uuid,'rejected') is not null,'Suppressed draft remains rejectable');
select lift_suppression(current_setting('test.suppression')::uuid,'Synthetic resolved');
select pg_temp.assert_ok((select lifted_at is not null and lift_reason='Synthetic resolved' and reason='Synthetic stop' from suppression_entries where id=current_setting('test.suppression')::uuid),'Suppression lift preserves history');
update contacts set email_verified=false where id='90000000-0000-4000-8000-000000000004';
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'verified current recipient','Lost verification blocks review');
update contacts set email_verified=true,email='changed@example.invalid' where id='90000000-0000-4000-8000-000000000004';
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'verified current recipient','Changed recipient blocks stale snapshot');
update contacts set email='buyer@example.invalid' where id='90000000-0000-4000-8000-000000000004';
update workspace_sales_config set outreach_rules='{}' where workspace_id=current_setting('test.workspace')::uuid;
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'current workspace policy','Revoked policy blocks old receipt');
update workspace_sales_config set outreach_rules='{"regionPolicyBasis":{"US":{"status":"verified","reference":"Synthetic acceptance only"}}}' where workspace_id=current_setting('test.workspace')::uuid;
select pg_temp.assert_ok(review_outreach_revision(current_setting('test.outreach')::uuid,current_setting('test.revision')::uuid,'approved') is not null,'Owner approves eligible exact revision');
select pg_temp.assert_ok((select status='approved' and held_at is not null and sent_at is null and provider_message_id is null from outreach where id=current_setting('test.outreach')::uuid),'Approved revision stays held, no delivery');
insert into outreach_revisions(workspace_id,outreach_id,revision_number,subject,body,reason_to_contact,evidence_snapshot,recipient_snapshot,compliance_snapshot,content_hash,created_by)
select workspace_id,outreach_id,2,subject,body||' Revision two',reason_to_contact,evidence_snapshot,recipient_snapshot,compliance_snapshot,'acceptance-hash-2',auth.uid() from outreach_revisions where id=current_setting('test.revision')::uuid;
update outreach set current_revision_id=(select id from outreach_revisions where outreach_id=outreach.id and revision_number=2) where id=current_setting('test.outreach')::uuid;
select pg_temp.assert_ok((select approved_revision_id is null and status='ready' from outreach where id=current_setting('test.outreach')::uuid),'New revision invalidates approval');
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'stale outreach revision','Old revision approval rejected');
select set_config('test.revision',(select current_revision_id::text from outreach where id=current_setting('test.outreach')::uuid),true);
insert into proof_points(id,workspace_id,client_name,approved_claim,approved) values('90000000-0000-4000-8000-000000000006',current_setting('test.workspace')::uuid,'Synthetic fixture','Synthetic approved claim',true);
select pg_temp.expect_error(format('insert into outreach_revisions(workspace_id,outreach_id,revision_number,body,reason_to_contact,content_hash,proof_snapshot) values(%L,%L,3,%L,%L,%L,%L)',current_setting('test.workspace'),current_setting('test.outreach'),'Synthetic','Synthetic','forged','[{"proofPointId":"90000000-0000-4000-8000-000000000006","approvedClaim":"Invented claim"}]'),'proof_snapshot_must_reference_exact','Fabricated proof rejected');
reset role;
update workspace_members set role='member' where workspace_id=current_setting('test.workspace')::uuid and user_id='90000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.assert_ok(update_native_pipeline(current_setting('test.workspace')::uuid,'90000000-0000-4000-8000-000000000003',1,'ready','Synthetic member action',null)=2,'Member pipeline operates');
select pg_temp.expect_error(format('select review_outreach_revision(%L,%L,%L)',current_setting('test.outreach'),current_setting('test.revision'),'approved'),'workspace admin required','Member cannot approve');
select pg_temp.expect_error('update proof_points set approved_claim=''Member changed trusted claim'' where id=''90000000-0000-4000-8000-000000000006''','Only workspace Owner/Admin','Member cannot change approved proof');
select pg_temp.expect_error('select add_suppression(''account'',''90000000-0000-4000-8000-000000000003'',null,null,''Member stop'',''acceptance'')','workspace admin required','Member cannot suppress');
insert into durable_jobs(workspace_id,job_type,idempotency_key) values(current_setting('test.workspace')::uuid,'discovery','acceptance-discovery');
select pg_temp.assert_ok((select count(*)=1 from durable_jobs),'Member queues discovery');
select pg_temp.expect_error(format('insert into durable_jobs(workspace_id,job_type,idempotency_key) values(%L,%L,%L)',current_setting('test.workspace'),'send_outreach','bad'),'check constraint','Send-like jobs denied');
select pg_temp.assert_ok((select outreach_id is not null from create_held_outreach_revision('90000000-0000-4000-8000-000000000003','90000000-0000-4000-8000-000000000004','Synthetic member','Synthetic held body','research','Synthetic reason','[{"id":"90000000-0000-4000-8000-000000000005"}]','[]','{"email":"buyer@example.invalid","emailVerified":true}','{"humanApprovalRequired":true,"autonomousSendEnabled":false}','acceptance-member-hash')),'Member prepares held draft');
select pg_temp.expect_error('select * from create_held_outreach_revision(''90000000-0000-4000-8000-000000000003'',''90000000-0000-4000-8000-000000000004'',''Synthetic'',''Synthetic'',''research'',''Synthetic'',''[]'',''[]'',''{}'',''{}'',''no-evidence'')','missing_evidence','No evidence blocks draft');
select pg_temp.expect_error('select * from create_held_outreach_revision(''90000000-0000-4000-8000-000000000003'',''90000000-0000-4000-8000-000000000004'',''Synthetic'',''Synthetic'',''research'',''Synthetic'',''[{"id":"90000000-0000-4000-8000-000000000005"}]'',''[]'',''{}'',''{"autonomousSendEnabled":true}'',''autonomous'')','autonomous_send_disabled','Autonomous draft flag rejected');
with changed as (update outreach_revisions set body='Tampered' where id=current_setting('test.revision')::uuid returning id) select pg_temp.assert_ok((select count(*)=0 from changed),'Revision mutation denied by RLS');
with changed as (update workspace_sales_config set outreach_rules='{}' where workspace_id=current_setting('test.workspace')::uuid returning workspace_id) select pg_temp.assert_ok((select count(*)=0 from changed),'Member cannot change policy');
reset role;
update workspace_members set role='viewer' where workspace_id=current_setting('test.workspace')::uuid and user_id='90000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.assert_ok((select count(*)=1 from accounts),'Viewer reads own accounts');
select pg_temp.expect_error(format('insert into accounts(workspace_id,domain,name) values(%L,%L,%L)',current_setting('test.workspace'),'viewer.example.invalid','Viewer write'),'row-level security','Viewer cannot create account');
select pg_temp.expect_error(format('select update_native_pipeline(%L,%L,2,%L,%L,null)',current_setting('test.workspace'),'90000000-0000-4000-8000-000000000003','ready','Viewer mutation'),'workspace operator required','Viewer cannot operate pipeline');
select pg_temp.expect_error(format('insert into durable_jobs(workspace_id,job_type,idempotency_key) values(%L,%L,%L)',current_setting('test.workspace'),'discovery','viewer-job'),'row-level security','Viewer cannot queue discovery');
reset role;
update workspace_members set role='admin' where workspace_id=current_setting('test.workspace')::uuid and user_id='90000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.assert_ok(review_outreach_revision(current_setting('test.outreach')::uuid,current_setting('test.revision')::uuid,'approved') is not null,'Admin reviews exact revision');
select json_build_object('passed',count(*),'checks',json_agg(check_name order by check_name)) from acceptance_results;
rollback;
